/********************************************************************
* /direct/star+u/sheppel/femtoAnalysis/femtoLibrary/dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /direct/star+u/sheppel/femtoAnalysis/femtoLibrary/dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledict();
extern void G__cpp_setup_inheritancedict();
extern void G__cpp_setup_typetabledict();
extern void G__cpp_setup_memvardict();
extern void G__cpp_setup_globaldict();
extern void G__cpp_setup_memfuncdict();
extern void G__cpp_setup_funcdict();
extern void G__set_cpp_environmentdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/direct/star+u/sheppel/femtoAnalysis/femtoLibrary/CumulantProfileContainer.h"
#include "/direct/star+u/sheppel/femtoAnalysis/femtoLibrary/analysisUtil.h"
#include "/direct/star+u/sheppel/femtoAnalysis/femtoLibrary/MomentFunctions.h"
#include "/direct/star+u/sheppel/femtoAnalysis/femtoLibrary/InputParameterList.h"
#include "/direct/star+u/sheppel/femtoAnalysis/femtoLibrary/EventLoop.h"
#include "/direct/star+u/sheppel/femtoAnalysis/femtoLibrary/ProtonEfficiency.h"
#include "/direct/star+u/sheppel/femtoAnalysis/femtoLibrary/StFemtoTrack.h"
#include "/direct/star+u/sheppel/femtoAnalysis/femtoLibrary/StFemtoEvent.h"
#include "/direct/star+u/sheppel/femtoAnalysis/femtoLibrary/QALoop.h"
#include "/direct/star+u/sheppel/femtoAnalysis/femtoLibrary/MomentEventLoop.h"
#include "/direct/star+u/sheppel/femtoAnalysis/femtoLibrary/SystematicEventLoop.h"
#include "/direct/star+u/sheppel/femtoAnalysis/femtoLibrary/FlucContainer.h"
#include "/direct/star+u/sheppel/femtoAnalysis/femtoLibrary/PileUpCorrection.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dictLN_TClass;
extern G__linked_taginfo G__dictLN_TBuffer;
extern G__linked_taginfo G__dictLN_TMemberInspector;
extern G__linked_taginfo G__dictLN_TObject;
extern G__linked_taginfo G__dictLN_TString;
extern G__linked_taginfo G__dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__dictLN_string;
extern G__linked_taginfo G__dictLN_TH1F;
extern G__linked_taginfo G__dictLN_TFile;
extern G__linked_taginfo G__dictLN_TGraphErrors;
extern G__linked_taginfo G__dictLN_CumulantProfileContainer;
extern G__linked_taginfo G__dictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__dictLN_vectorlETProfilemUcOallocatorlETProfilemUgRsPgR;
extern G__linked_taginfo G__dictLN_vectorlETGraphErrorsmUcOallocatorlETGraphErrorsmUgRsPgR;
extern G__linked_taginfo G__dictLN_maplETStringcOdoublecOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__dictLN_TChain;
extern G__linked_taginfo G__dictLN_InputParameterList;
extern G__linked_taginfo G__dictLN_vectorlECumulantProfileContainermUcOallocatorlECumulantProfileContainermUgRsPgR;
extern G__linked_taginfo G__dictLN_pairlEboolcOboolgR;
extern G__linked_taginfo G__dictLN_vectorlEpairlEintcOdoublegRcOallocatorlEpairlEintcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__dictLN_ProtonEfficiency;
extern G__linked_taginfo G__dictLN_TRandom3;
extern G__linked_taginfo G__dictLN_TH2F;
extern G__linked_taginfo G__dictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR;
extern G__linked_taginfo G__dictLN_vectorlETF1mUcOallocatorlETF1mUgRsPgR;
extern G__linked_taginfo G__dictLN_StFemtoTrack;
extern G__linked_taginfo G__dictLN_StFemtoEvent;
extern G__linked_taginfo G__dictLN_vectorlEStFemtoTrackcOallocatorlEStFemtoTrackgRsPgR;
extern G__linked_taginfo G__dictLN_FlucContainer;
extern G__linked_taginfo G__dictLN_PileUpCorrection;
extern G__linked_taginfo G__dictLN_PileUpCorrectioncLcLdA;

/* STUB derived class for protected member access */
